# Assignment 3

**Please follow the instructions. Do not add new cell! Write your code in designated areas.**

In [33]:
import datetime
import socket

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 3: Solutions by Nkem Mbachu') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

Assignment 3: Solutions by Nkem Mbachu
Local Time: 2023-07-02 14:54:05
Computer ID: Nkem

## NumPy

1. Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array.

In [26]:
## Your code here down
import numpy as np

# Create a 2D array of size 4x5 with random integers between 1 and 10
array = np.random.randint(1, 11, size=(4, 5))

# Find the maximum value of the entire array
max_value = np.max(array)

print("Array:")
print(array)
print("\nMaximum value:", max_value)

# print(mean)
# Find the mean value of the entire array
mean_value = np.mean(array)

print("\nMean value:", mean_value)

#print(std) and so on
# Find the standard deviation value of the entire array
std_value = np.std(array)

print("\nStandard deviation value:", std_value)

## Your code here up

Array:
[[ 2  8  6  7  2]
 [ 4  6  6  4  6]
 [10  6 10  4  8]
 [ 3  3  3  7  2]]

Maximum value: 10

Mean value: 5.35

Standard deviation value: 2.4550967394381833

2. Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

In [39]:
## Your code here down

# Create a 1D array of size 20 with random floats between 0 and 1
array_1d = np.random.random(20)

# Reshape the array into a 4x5 matrix
array_2d = array_1d.reshape(4, 5)

# Compute the mean of each row
row_means = np.mean(array_2d, axis=1)

print("1D Array:")
print(array_1d)
print("\nReshaped 2D Array:")
print(array_2d)
print("\nMean of each row:")
print(row_means)

## Your code here up

1D Array:
[0.63326025 0.36787947 0.87530301 0.30918317 0.38685579 0.34142941
 0.59758117 0.25474287 0.1477008  0.59113165 0.56017748 0.68214654
 0.67213989 0.78009715 0.03289022 0.10633937 0.23977222 0.45744658
 0.18880593 0.09588236]

Reshaped 2D Array:
[[0.63326025 0.36787947 0.87530301 0.30918317 0.38685579]
 [0.34142941 0.59758117 0.25474287 0.1477008  0.59113165]
 [0.56017748 0.68214654 0.67213989 0.78009715 0.03289022]
 [0.10633937 0.23977222 0.45744658 0.18880593 0.09588236]]

Mean of each row:
[0.51449634 0.38651718 0.54549026 0.21764929]

3. Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

In [40]:
## Your code here down

# Create a 2D array of size 5x5 with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 5))

# Compute the standard deviation of each column
column_std = np.std(array, axis=0)

print("Array:")
print(array)
print("\nStandard Deviation of Each Column:")
print(column_std)

## Your code here up

Array:
[[67 43  1 92 37]
 [ 5 62 10 17 13]
 [41 69 30 71 99]
 [33 29 68 43 69]
 [36 25 64 66 93]]

Standard Deviation of Each Column:
[19.77473135 17.45393938 27.33203249 25.6702162  32.87795614]

4. Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

In [36]:
## Your code here down

# Create a 1D array of size 15 with random floats between -10 and 10
array = np.random.uniform(-10, 10, size=15)

# Replace negative values with their absolute values
array_abs = np.abs(array)

print("Array before replacing negative values:")
print(array)
print("\nArray after replacing negative values:")
print(array_abs)

## Your code here up

Array before replacing negative values:
[ 2.44340538 -9.70819366 -1.12792784  9.42650401 -8.83485151  3.16969217
 -8.88985824 -4.43698681  9.64774957  4.07318397  3.15083089 -2.8301601
  9.63321878 -8.21066059  2.71737063]

Array after replacing negative values:
[2.44340538 9.70819366 1.12792784 9.42650401 8.83485151 3.16969217
 8.88985824 4.43698681 9.64774957 4.07318397 3.15083089 2.8301601
 9.63321878 8.21066059 2.71737063]

5. Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

In [41]:
## Your code here down

# Create a 2D array of size 3x4 with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 4))

# Calculate the sum of all elements in the array
array_sum = np.sum(array)

print("Array:")
print(array)
print("Sum of all elements:", array_sum)

## Your code here up

Array:
[[35 49 61  7]
 [79 28 87 84]
 [77 55 85 75]]
Sum of all elements: 722

7. Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

In [35]:
## Your code here down

# Create a 2D array of size 4x6 with random floats between 0 and 1
array = np.random.random((4, 6))

# Calculate the column mean
column_mean = np.mean(array, axis=0)

# Calculate the column standard deviation
column_std = np.std(array, axis=0)

# Normalize each column
normalized_array = (array - column_mean) / column_std

print("Array:")
print(array)
print("\nNormalized Array:")
print(normalized_array)

## Your code here up

Array:
[[0.24704652 0.71498669 0.4585545  0.0293996  0.95450595 0.02859237]
 [0.2536053  0.36829242 0.1638387  0.19745133 0.66112157 0.02414064]
 [0.27465042 0.6491581  0.14635284 0.02995713 0.7709699  0.33162746]
 [0.39437208 0.43763035 0.65461226 0.53311032 0.63976879 0.3957297 ]]

Normalized Array:
[[-7.59496113e-01  1.20111825e+00  4.83445332e-01 -8.17806712e-01
   1.58790871e+00 -9.77969897e-01]
 [-6.49706889e-01 -1.21333813e+00 -9.03684883e-01 -1.37520966e-04
  -7.65975675e-01 -1.00412896e+00]
 [-2.97426457e-01  7.42673200e-01 -9.85985070e-01 -8.15094013e-01
   1.15360493e-01  8.02711976e-01]
 [ 1.70662946e+00 -7.30453315e-01  1.40622462e+00  1.63303825e+00
  -9.37293527e-01  1.17938688e+00]]

8. Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

In [56]:
## Your code here down

# Create a 2D array of size 10x10 with random integers between 1 and 100
array = np.random.randint(1, 101, size=(10, 10))

print("Array:")
print(array)

# Replace values greater than 50 with 1 and all other values with 0
array[array <= 50] = 0
array[array > 50] = 1


print("\nArray:")
print(array)

## Your code here up

Array:
[[ 77  94  86  48  49  81  66  28  36  80]
 [ 72  16  12  17  36  14  17  66  45  33]
 [ 24  92  48  69  28  34  84  42  75  95]
 [  9   5  93  59  64  63  15  65  16  84]
 [ 84  78  68  90  83  88  13  53  31  79]
 [  5  77  35  37   3  78  14  15  31  57]
 [ 61  31  45  14  87  97  30  20 100  30]
 [ 41  14  19  24  42  96  94  16  17  25]
 [ 19  93  22  65  90  76  93  57  10  96]
 [ 64  39   4  15  23  19  21   8  91  57]]

Array:
[[1 1 1 0 0 1 1 0 0 1]
 [1 0 0 0 0 0 0 1 0 0]
 [0 1 0 1 0 0 1 0 1 1]
 [0 0 1 1 1 1 0 1 0 1]
 [1 1 1 1 1 1 0 1 0 1]
 [0 1 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 1 0 0 1 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1 1]]

9. Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

In [58]:
## Your code here down

# Create a 1D array of size 50 with random floats between 0 and 1
array = np.random.random(50)

# Find the number of elements greater than 0.5
count = np.sum(array > 0.5)

print("Array:")
print(array)
print("\nNumber of elements greater than 0.5:", count)

## Your code here up

Array:
[0.75565112 0.73756399 0.67758591 0.83507576 0.99076562 0.80918787
 0.20246437 0.34500776 0.21068665 0.37002162 0.10571156 0.22292032
 0.76599189 0.26928283 0.92818635 0.82476708 0.60189191 0.69226088
 0.31404159 0.47708139 0.96702464 0.83628845 0.23341953 0.76450472
 0.82357162 0.4428511  0.80955554 0.77907514 0.1985432  0.57481873
 0.95994677 0.93468774 0.3129125  0.19257302 0.66400218 0.93447654
 0.15446006 0.48040376 0.88517475 0.60558908 0.91887287 0.42062924
 0.01022087 0.68348528 0.28617189 0.04005145 0.82719788 0.27413308
 0.68487352 0.38601071]

Number of elements greater than 0.5: 28

10. Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

In [62]:
## Your code here down

# Create a 2D array of size 5x5 with random floats between -1 and 1
array = np.random.uniform(-1, 1, size=(5, 5))

# Find the absolute difference between the maximum and minimum values in each row
row_diff = np.abs(np.max(array, axis=1) - np.min(array, axis=1))

print("Array:")
print(array)
print("\nAbsolute difference between maximum and minimum values in each row:")
print(row_diff)

## Your code here up

Array:
[[-0.01667493 -0.80669254 -0.95406448 -0.68885159  0.21459937]
 [-0.81607916 -0.69417779  0.85054605 -0.36070468  0.18754224]
 [-0.97136804  0.35996692  0.30584427  0.29964062  0.11907245]
 [-0.72498308 -0.79209151  0.38093817 -0.4847692  -0.766458  ]
 [ 0.86191571 -0.97536206 -0.41848064  0.95981634  0.17884693]]

Absolute difference between maximum and minimum values in each row:
[1.16866385 1.66662521 1.33133496 1.17302968 1.9351784 ]

## Pandas

Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part.

In [77]:
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(40):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # rantom lat with 2 decimal points
        'temperature': round(random.uniform(18, 25), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 50), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)

In [80]:
df =pd.DataFrame(farms) # your code here
df.head()

  farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0    Farm 1   -103.59     51.31         22.8           29.6       brown
1    Farm 2   -102.20     51.36         21.2           36.2        gray
2    Farm 3   -103.72     51.43         22.2           42.5  dark brown
3    Farm 4   -103.23     51.99         23.0           43.9       brown
4    Farm 5   -104.41     50.22         23.4           37.2  dark brown

1. Select the rows where the temperature is above 20 degrees Celsius.

In [81]:
## Your code here down
df[df['temperature']>20]

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -103.59     51.31         22.8           29.6       brown
1     Farm 2   -102.20     51.36         21.2           36.2        gray
2     Farm 3   -103.72     51.43         22.2           42.5  dark brown
3     Farm 4   -103.23     51.99         23.0           43.9       brown
4     Farm 5   -104.41     50.22         23.4           37.2  dark brown
6     Farm 7   -102.88     51.65         24.0           36.6        gray
8     Farm 9   -101.78     51.86         20.8           24.4       brown
10   Farm 11   -103.06     51.08         23.0           30.5       black
11   Farm 12   -101.88     51.94         21.3           28.7        gray
12   Farm 13   -102.56     51.36         22.6           49.9        gray
17   Farm 18   -104.96     51.31         24.5           43.6       brown
18   Farm 19   -104.24     50.77         22.7           38.4       brown
20   Farm 21   -102.42     50.51         23.9           36.9        gray
21   Farm 22   -103.77     50.23         22.8           28.8       brown
22   Farm 23   -101.29     51.96         21.8           47.1       black
23   Farm 24   -103.17     50.01         23.4           37.2        None
24   Farm 25   -101.83     51.31         24.5           37.1        gray
25   Farm 26   -104.84     51.46         22.8           23.2        None
26   Farm 27   -102.56     51.33         21.2           38.8        gray
28   Farm 29   -100.89     51.65         24.4           31.9  dark brown
29   Farm 30   -102.37     50.04         24.4           25.4  dark brown
31   Farm 32   -102.12     51.08         22.6           39.1  dark brown
33   Farm 34   -100.43     50.94         22.8           27.1       brown
34   Farm 35   -100.40     51.40         22.5           33.1        None
35   Farm 36   -104.24     50.28         25.0           36.5       black
36   Farm 37   -103.81     50.72         23.6           29.7        gray
38   Farm 39   -100.44     50.29         24.3           29.3       black
39   Farm 40   -104.90     51.95         21.3           24.8       black

2. Sort the DataFrame by precipitation in descending order.

In [82]:
## Your code here down
df.sort_values(by='precipitation', ascending=False)  # Descending order

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
12   Farm 13   -102.56     51.36         22.6           49.9        gray
7     Farm 8   -101.80     51.90         19.0           49.2        gray
13   Farm 14   -102.98     51.90         19.9           48.8        gray
22   Farm 23   -101.29     51.96         21.8           47.1       black
3     Farm 4   -103.23     51.99         23.0           43.9       brown
17   Farm 18   -104.96     51.31         24.5           43.6       brown
2     Farm 3   -103.72     51.43         22.2           42.5  dark brown
16   Farm 17   -102.51     50.11         19.8           41.2       black
27   Farm 28   -101.35     51.08         19.6           40.1       black
19   Farm 20   -103.53     50.34         19.9           39.5  dark brown
31   Farm 32   -102.12     51.08         22.6           39.1  dark brown
26   Farm 27   -102.56     51.33         21.2           38.8        gray
18   Farm 19   -104.24     50.77         22.7           38.4       brown
4     Farm 5   -104.41     50.22         23.4           37.2  dark brown
23   Farm 24   -103.17     50.01         23.4           37.2        None
24   Farm 25   -101.83     51.31         24.5           37.1        gray
20   Farm 21   -102.42     50.51         23.9           36.9        gray
6     Farm 7   -102.88     51.65         24.0           36.6        gray
35   Farm 36   -104.24     50.28         25.0           36.5       black
1     Farm 2   -102.20     51.36         21.2           36.2        gray
32   Farm 33   -103.96     50.33         19.0           35.0        gray
30   Farm 31   -101.40     51.61         18.8           34.1  dark brown
34   Farm 35   -100.40     51.40         22.5           33.1        None
28   Farm 29   -100.89     51.65         24.4           31.9  dark brown
10   Farm 11   -103.06     51.08         23.0           30.5       black
14   Farm 15   -102.94     50.64         19.7           30.4        gray
36   Farm 37   -103.81     50.72         23.6           29.7        gray
0     Farm 1   -103.59     51.31         22.8           29.6       brown
38   Farm 39   -100.44     50.29         24.3           29.3       black
21   Farm 22   -103.77     50.23         22.8           28.8       brown
11   Farm 12   -101.88     51.94         21.3           28.7        gray
5     Farm 6   -101.83     51.88         18.4           28.1       black
33   Farm 34   -100.43     50.94         22.8           27.1       brown
29   Farm 30   -102.37     50.04         24.4           25.4  dark brown
39   Farm 40   -104.90     51.95         21.3           24.8       black
8     Farm 9   -101.78     51.86         20.8           24.4       brown
37   Farm 38   -104.77     51.76         19.6           23.4  dark brown
25   Farm 26   -104.84     51.46         22.8           23.2        None
9    Farm 10   -102.29     50.72         18.3           20.4  dark brown
15   Farm 16   -100.59     51.23         19.3           20.1       brown

3. Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.

In [83]:
## Your code here down
df.loc[(df['farm_lat'] >= 51.00) & (df['farm_lat'] <= 51.15)]

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
10   Farm 11   -103.06     51.08         23.0           30.5       black
27   Farm 28   -101.35     51.08         19.6           40.1       black
31   Farm 32   -102.12     51.08         22.6           39.1  dark brown

 4. Calculate the standard deviation of precipitation for each soil type.

In [89]:
## Your code here down
std_deviation = df.groupby('soil_type')['precipitation'].std()

print("Standard Deviation of Precipitation for Each Soil Type:")
print(std_deviation)

## Your code here up

Standard Deviation of Precipitation for Each Soil Type:
soil_type
black         7.716217
brown         8.916347
dark brown    7.882646
gray          7.468413
Name: precipitation, dtype: float64

5. Calculate the cumulative sum of precipitation for each soil type.

In [93]:
## Your code here down
cumulative_sum = df.groupby('soil_type')['precipitation'].cumsum()

print("Cumulative Sum of Precipitation for Each Soil Type:")
print(cumulative_sum)

## Your code here up

Cumulative Sum of Precipitation for Each Soil Type:
0      29.6
1      36.2
2      42.5
3      73.5
4      79.7
5      28.1
6      72.8
7     122.0
8      97.9
9     100.1
10     58.6
11    150.7
12    200.6
13    249.4
14    279.8
15    118.0
16     99.8
17    161.6
18    200.0
19    139.6
20    316.7
21    228.8
22    146.9
23      NaN
24    353.8
25      NaN
26    392.6
27    187.0
28    171.5
29    196.9
30    231.0
31    270.1
32    427.6
33    255.9
34      NaN
35    223.5
36    457.3
37    293.5
38    252.8
39    277.6
Name: precipitation, dtype: float64

6. Determine the top 3 farms with the highest average temperature.

In [99]:
## Your code here down
# Calculate the average temperature for each farm
average_temp = df.groupby('farm_name')['temperature'].mean()

# Sort the farms based on average temperature in descending order
sorted_farms = average_temp.sort_values(ascending=False)

# Get the top 3 farms with the highest average temperature
top_3_farms = sorted_farms.head(3)

print("Top 3 Farms with the Highest Average Temperature:")
print(top_3_farms)

## Your code here up

Top 3 Farms with the Highest Average Temperature:
farm_name
Farm 36    25.0
Farm 18    24.5
Farm 25    24.5
Name: temperature, dtype: float64

7. Find famrs in each soil type that have the highest temperature.

In [101]:
## Your code here down
max_temp_farms = df.groupby('soil_type').apply(lambda x: x[x['temperature'] == x['temperature'].max()])

print("Farms with the Highest Temperature in Each Soil Type:")
print(max_temp_farms)

## Your code here up

Farms with the Highest Temperature in Each Soil Type:
              farm_name  farm_lon  farm_lat  temperature  precipitation  \
soil_type
black      35   Farm 36   -104.24     50.28         25.0           36.5
brown      17   Farm 18   -104.96     51.31         24.5           43.6
dark brown 28   Farm 29   -100.89     51.65         24.4           31.9
           29   Farm 30   -102.37     50.04         24.4           25.4
gray       24   Farm 25   -101.83     51.31         24.5           37.1

                soil_type
soil_type
black      35       black
brown      17       brown
dark brown 28  dark brown
           29  dark brown
gray       24        gray

8. Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

In [102]:
## Your code here down
total_precipitation = df['precipitation'].sum()

# Calculate the percentage contribution of each farm's precipitation
df['percentage_tot_prec'] = (df['precipitation'] / total_precipitation) * 100

print("DataFrame with Percentage Contribution of Precipitation:")
print(df)

## Your code here up

DataFrame with Percentage Contribution of Precipitation:
   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -103.59     51.31         22.8           29.6       brown
1     Farm 2   -102.20     51.36         21.2           36.2        gray
2     Farm 3   -103.72     51.43         22.2           42.5  dark brown
3     Farm 4   -103.23     51.99         23.0           43.9       brown
4     Farm 5   -104.41     50.22         23.4           37.2  dark brown
5     Farm 6   -101.83     51.88         18.4           28.1       black
6     Farm 7   -102.88     51.65         24.0           36.6        gray
7     Farm 8   -101.80     51.90         19.0           49.2        gray
8     Farm 9   -101.78     51.86         20.8           24.4       brown
9    Farm 10   -102.29     50.72         18.3           20.4  dark brown
10   Farm 11   -103.06     51.08         23.0           30.5       black
11   Farm 12   -101.88     51.94         21.3           28.7        gray
12   Farm 13   -102.56     51.36         22.6           49.9        gray
13   Farm 14   -102.98     51.90         19.9           48.8        gray
14   Farm 15   -102.94     50.64         19.7           30.4        gray
15   Farm 16   -100.59     51.23         19.3           20.1       brown
16   Farm 17   -102.51     50.11         19.8           41.2       black
17   Farm 18   -104.96     51.31         24.5           43.6       brown
18   Farm 19   -104.24     50.77         22.7           38.4       brown
19   Farm 20   -103.53     50.34         19.9           39.5  dark brown
20   Farm 21   -102.42     50.51         23.9           36.9        gray
21   Farm 22   -103.77     50.23         22.8           28.8       brown
22   Farm 23   -101.29     51.96         21.8           47.1       black
23   Farm 24   -103.17     50.01         23.4           37.2        None
24   Farm 25   -101.83     51.31         24.5           37.1        gray
25   Farm 26   -104.84     51.46         22.8           23.2        None
26   Farm 27   -102.56     51.33         21.2           38.8        gray
27   Farm 28   -101.35     51.08         19.6           40.1       black
28   Farm 29   -100.89     51.65         24.4           31.9  dark brown
29   Farm 30   -102.37     50.04         24.4           25.4  dark brown
30   Farm 31   -101.40     51.61         18.8           34.1  dark brown
31   Farm 32   -102.12     51.08         22.6           39.1  dark brown
32   Farm 33   -103.96     50.33         19.0           35.0        gray
33   Farm 34   -100.43     50.94         22.8           27.1       brown
34   Farm 35   -100.40     51.40         22.5           33.1        None
35   Farm 36   -104.24     50.28         25.0           36.5       black
36   Farm 37   -103.81     50.72         23.6           29.7        gray
37   Farm 38   -104.77     51.76         19.6           23.4  dark brown
38   Farm 39   -100.44     50.29         24.3           29.3       black
39   Farm 40   -104.90     51.95         21.3           24.8       black

    percentage_tot_prec
0              2.148352
1              2.627377
2              3.084628
3              3.186239
4              2.699956
5              2.039483
6              2.656409
7              3.570910
8              1.770939
9              1.480621
10             2.213674
11             2.083031
12             3.621716
13             3.541878
14             2.206416
15             1.458847
16             2.990274
17             3.164465
18             2.787052
19             2.866889
20             2.678183
21             2.090289
22             3.418493
23             2.699956
24             2.692699
25             1.683844
26             2.816084
27             2.910437
28             2.315285
29             1.843519
30             2.474960
31             2.837857
32             2.540282
33             1.966904
34             2.402381
35             2.649151
36             2.155610
37             1.698360
38             2.126579
39             1.799971

9. Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.

In [105]:
## Your code here down
df['precipitation_rank'] = df['precipitation'].rank(method='min')

print("DataFrame with Precipitation Ranks:")
print(df)

## Your code here up

DataFrame with Precipitation Ranks:
   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -103.59     51.31         22.8           29.6       brown
1     Farm 2   -102.20     51.36         21.2           36.2        gray
2     Farm 3   -103.72     51.43         22.2           42.5  dark brown
3     Farm 4   -103.23     51.99         23.0           43.9       brown
4     Farm 5   -104.41     50.22         23.4           37.2  dark brown
5     Farm 6   -101.83     51.88         18.4           28.1       black
6     Farm 7   -102.88     51.65         24.0           36.6        gray
7     Farm 8   -101.80     51.90         19.0           49.2        gray
8     Farm 9   -101.78     51.86         20.8           24.4       brown
9    Farm 10   -102.29     50.72         18.3           20.4  dark brown
10   Farm 11   -103.06     51.08         23.0           30.5       black
11   Farm 12   -101.88     51.94         21.3           28.7        gray
12   Farm 13   -102.56     51.36         22.6           49.9        gray
13   Farm 14   -102.98     51.90         19.9           48.8        gray
14   Farm 15   -102.94     50.64         19.7           30.4        gray
15   Farm 16   -100.59     51.23         19.3           20.1       brown
16   Farm 17   -102.51     50.11         19.8           41.2       black
17   Farm 18   -104.96     51.31         24.5           43.6       brown
18   Farm 19   -104.24     50.77         22.7           38.4       brown
19   Farm 20   -103.53     50.34         19.9           39.5  dark brown
20   Farm 21   -102.42     50.51         23.9           36.9        gray
21   Farm 22   -103.77     50.23         22.8           28.8       brown
22   Farm 23   -101.29     51.96         21.8           47.1       black
23   Farm 24   -103.17     50.01         23.4           37.2        None
24   Farm 25   -101.83     51.31         24.5           37.1        gray
25   Farm 26   -104.84     51.46         22.8           23.2        None
26   Farm 27   -102.56     51.33         21.2           38.8        gray
27   Farm 28   -101.35     51.08         19.6           40.1       black
28   Farm 29   -100.89     51.65         24.4           31.9  dark brown
29   Farm 30   -102.37     50.04         24.4           25.4  dark brown
30   Farm 31   -101.40     51.61         18.8           34.1  dark brown
31   Farm 32   -102.12     51.08         22.6           39.1  dark brown
32   Farm 33   -103.96     50.33         19.0           35.0        gray
33   Farm 34   -100.43     50.94         22.8           27.1       brown
34   Farm 35   -100.40     51.40         22.5           33.1        None
35   Farm 36   -104.24     50.28         25.0           36.5       black
36   Farm 37   -103.81     50.72         23.6           29.7        gray
37   Farm 38   -104.77     51.76         19.6           23.4  dark brown
38   Farm 39   -100.44     50.29         24.3           29.3       black
39   Farm 40   -104.90     51.95         21.3           24.8       black

    percentage_tot_prec  precipitation_rank
0              2.148352                13.0
1              2.627377                21.0
2              3.084628                34.0
3              3.186239                36.0
4              2.699956                26.0
5              2.039483                 9.0
6              2.656409                23.0
7              3.570910                39.0
8              1.770939                 5.0
9              1.480621                 2.0
10             2.213674                16.0
11             2.083031                10.0
12             3.621716                40.0
13             3.541878                38.0
14             2.206416                15.0
15             1.458847                 1.0
16             2.990274                33.0
17             3.164465                35.0
18             2.787052                28.0
19             2.866889                31.0
20             2.678183                24.0
21             2.090289                11.0
22             3.418493                37.0
23             2.699956                26.0
24             2.692699                25.0
25             1.683844                 3.0
26             2.816084                29.0
27             2.910437                32.0
28             2.315285                17.0
29             1.843519                 7.0
30             2.474960                19.0
31             2.837857                30.0
32             2.540282                20.0
33             1.966904                 8.0
34             2.402381                18.0
35             2.649151                22.0
36             2.155610                14.0
37             1.698360                 4.0
38             2.126579                12.0
39             1.799971                 6.0

10. Normalize the temperature column to a range between 0 and 1 for each farm.

In [108]:
## Your code here down
grouped_data = df.groupby('farm_name')

# Calculate the minimum and maximum temperature for each farm
min_temp = grouped_data['temperature'].transform('min')
max_temp = grouped_data['temperature'].transform('max')


# Normalize the temperature column between 0 and 1 for each farm
df['temperature'] = (df['temperature'] - min_temp) / (max_temp - min_temp)

print("DataFrame with Normalized Temperature:")
print(df)

## Your code here up

DataFrame with Normalized Temperature:
   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -103.59     51.31          NaN           29.6       brown
1     Farm 2   -102.20     51.36          NaN           36.2        gray
2     Farm 3   -103.72     51.43          NaN           42.5  dark brown
3     Farm 4   -103.23     51.99          NaN           43.9       brown
4     Farm 5   -104.41     50.22          NaN           37.2  dark brown
5     Farm 6   -101.83     51.88          NaN           28.1       black
6     Farm 7   -102.88     51.65          NaN           36.6        gray
7     Farm 8   -101.80     51.90          NaN           49.2        gray
8     Farm 9   -101.78     51.86          NaN           24.4       brown
9    Farm 10   -102.29     50.72          NaN           20.4  dark brown
10   Farm 11   -103.06     51.08          NaN           30.5       black
11   Farm 12   -101.88     51.94          NaN           28.7        gray
12   Farm 13   -102.56     51.36          NaN           49.9        gray
13   Farm 14   -102.98     51.90          NaN           48.8        gray
14   Farm 15   -102.94     50.64          NaN           30.4        gray
15   Farm 16   -100.59     51.23          NaN           20.1       brown
16   Farm 17   -102.51     50.11          NaN           41.2       black
17   Farm 18   -104.96     51.31          NaN           43.6       brown
18   Farm 19   -104.24     50.77          NaN           38.4       brown
19   Farm 20   -103.53     50.34          NaN           39.5  dark brown
20   Farm 21   -102.42     50.51          NaN           36.9        gray
21   Farm 22   -103.77     50.23          NaN           28.8       brown
22   Farm 23   -101.29     51.96          NaN           47.1       black
23   Farm 24   -103.17     50.01          NaN           37.2        None
24   Farm 25   -101.83     51.31          NaN           37.1        gray
25   Farm 26   -104.84     51.46          NaN           23.2        None
26   Farm 27   -102.56     51.33          NaN           38.8        gray
27   Farm 28   -101.35     51.08          NaN           40.1       black
28   Farm 29   -100.89     51.65          NaN           31.9  dark brown
29   Farm 30   -102.37     50.04          NaN           25.4  dark brown
30   Farm 31   -101.40     51.61          NaN           34.1  dark brown
31   Farm 32   -102.12     51.08          NaN           39.1  dark brown
32   Farm 33   -103.96     50.33          NaN           35.0        gray
33   Farm 34   -100.43     50.94          NaN           27.1       brown
34   Farm 35   -100.40     51.40          NaN           33.1        None
35   Farm 36   -104.24     50.28          NaN           36.5       black
36   Farm 37   -103.81     50.72          NaN           29.7        gray
37   Farm 38   -104.77     51.76          NaN           23.4  dark brown
38   Farm 39   -100.44     50.29          NaN           29.3       black
39   Farm 40   -104.90     51.95          NaN           24.8       black

    percentage_tot_prec  precipitation_rank  normalized_temp
0              2.148352                13.0              NaN
1              2.627377                21.0              NaN
2              3.084628                34.0              NaN
3              3.186239                36.0              NaN
4              2.699956                26.0              NaN
5              2.039483                 9.0              NaN
6              2.656409                23.0              NaN
7              3.570910                39.0              NaN
8              1.770939                 5.0              NaN
9              1.480621                 2.0              NaN
10             2.213674                16.0              NaN
11             2.083031                10.0              NaN
12             3.621716                40.0              NaN
13             3.541878                38.0              NaN
14             2.206416                15.0              NaN
15             1.458847                 1.0              NaN
16             2.990274                33.0              NaN
17             3.164465                35.0              NaN
18             2.787052                28.0              NaN
19             2.866889                31.0              NaN
20             2.678183                24.0              NaN
21             2.090289                11.0              NaN
22             3.418493                37.0              NaN
23             2.699956                26.0              NaN
24             2.692699                25.0              NaN
25             1.683844                 3.0              NaN
26             2.816084                29.0              NaN
27             2.910437                32.0              NaN
28             2.315285                17.0              NaN
29             1.843519                 7.0              NaN
30             2.474960                19.0              NaN
31             2.837857                30.0              NaN
32             2.540282                20.0              NaN
33             1.966904                 8.0              NaN
34             2.402381                18.0              NaN
35             2.649151                22.0              NaN
36             2.155610                14.0              NaN
37             1.698360                 4.0              NaN
38             2.126579                12.0              NaN
39             1.799971                 6.0              NaN