# Assignment 3

**Please follow the instructions. Do not add new cell! Write your code in designated areas.**

In [112]:
import datetime
import socket

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 3: Solutions by Nkem Mbachu') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

Assignment 3: Solutions by Nkem Mbachu
Local Time: 2023-07-04 20:14:27
Computer ID: Nkem

## NumPy

1. Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array.

In [113]:
## Your code here down
import numpy as np

# Create a 2D array of size 4x5 with random integers between 1 and 10
array = np.random.randint(1, 11, size=(4, 5))

# Find the maximum value of the entire array
max_value = np.max(array)

print("Array:")
print(array)
print("\nMaximum value:", max_value)

# print(mean)
# Find the mean value of the entire array
mean_value = np.mean(array)

print("\nMean value:", mean_value)

#print(std) and so on
# Find the standard deviation value of the entire array
std_value = np.std(array)

print("\nStandard deviation value:", std_value)

## Your code here up

Array:
[[ 8  3  8  1  6]
 [ 1 10 10  4  5]
 [ 7  3  7 10  6]
 [ 3  1  1  6 10]]

Maximum value: 10

Mean value: 5.5

Standard deviation value: 3.170173496829472

2. Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

In [114]:
## Your code here down

# Create a 1D array of size 20 with random floats between 0 and 1
array_1d = np.random.random(20)

# Reshape the array into a 4x5 matrix
array_2d = array_1d.reshape(4, 5)

# Compute the mean of each row
row_means = np.mean(array_2d, axis=1)

print("1D Array:")
print(array_1d)
print("\nReshaped 2D Array:")
print(array_2d)
print("\nMean of each row:")
print(row_means)

## Your code here up

1D Array:
[0.49660915 0.45122833 0.13563896 0.27086894 0.55608263 0.00290193
 0.5031707  0.91925794 0.55891428 0.72817485 0.65645345 0.05111333
 0.58983551 0.30778811 0.27285437 0.02560711 0.05604933 0.90911565
 0.32265672 0.48269294]

Reshaped 2D Array:
[[0.49660915 0.45122833 0.13563896 0.27086894 0.55608263]
 [0.00290193 0.5031707  0.91925794 0.55891428 0.72817485]
 [0.65645345 0.05111333 0.58983551 0.30778811 0.27285437]
 [0.02560711 0.05604933 0.90911565 0.32265672 0.48269294]]

Mean of each row:
[0.3820856  0.54248394 0.37560896 0.35922435]

3. Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

In [115]:
## Your code here down

# Create a 2D array of size 5x5 with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 5))

# Compute the standard deviation of each column
column_std = np.std(array, axis=0)

print("Array:")
print(array)
print("\nStandard Deviation of Each Column:")
print(column_std)

## Your code here up

Array:
[[28 93 85 28 73]
 [87 44 39 26 91]
 [30 79  8 40 47]
 [45 39 22 42 19]
 [32 28 42 82 92]]

Standard Deviation of Each Column:
[22.1142488  24.95275536 25.9799923  20.21484603 27.95424834]

4. Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

In [116]:
## Your code here down

# Create a 1D array of size 15 with random floats between -10 and 10
array = np.random.uniform(-10, 10, size=15)

# Replace negative values with their absolute values
array_abs = np.abs(array)

print("Array before replacing negative values:")
print(array)
print("\nArray after replacing negative values:")
print(array_abs)

## Your code here up

Array before replacing negative values:
[ 7.75454803  0.77654977 -2.20731072 -2.78804626  3.94342849 -9.11064171
 -7.07402018  2.68219794  1.60724227  4.95864763  1.22430638 -0.61437126
  8.69792313 -5.01929942  1.25361366]

Array after replacing negative values:
[7.75454803 0.77654977 2.20731072 2.78804626 3.94342849 9.11064171
 7.07402018 2.68219794 1.60724227 4.95864763 1.22430638 0.61437126
 8.69792313 5.01929942 1.25361366]

5. Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

In [117]:
## Your code here down

# Create a 2D array of size 3x4 with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 4))

# Calculate the sum of all elements in the array
array_sum = np.sum(array)

print("Array:")
print(array)
print("Sum of all elements:", array_sum)

## Your code here up

Array:
[[30 36 86 35]
 [37 10 46 62]
 [62 81 23 61]]
Sum of all elements: 569

7. Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

In [118]:
## Your code here down

# Create a 2D array of size 4x6 with random floats between 0 and 1
array = np.random.random((4, 6))

# Calculate the column mean
column_mean = np.mean(array, axis=0)

# Calculate the column standard deviation
column_std = np.std(array, axis=0)

# Normalize each column
normalized_array = (array - column_mean) / column_std

print("Array:")
print(array)
print("\nNormalized Array:")
print(normalized_array)

## Your code here up

Array:
[[0.83007166 0.89815039 0.40771194 0.81588878 0.96613972 0.06891236]
 [0.91610082 0.67469043 0.98640923 0.91241358 0.08668887 0.28446045]
 [0.97063782 0.73484791 0.18770185 0.00649122 0.23293344 0.16278209]
 [0.42065717 0.91014481 0.94258537 0.94962907 0.37062782 0.48992867]]

Normalized Array:
[[ 0.21170951  0.91835984 -0.65185424  0.37430304  1.6520197  -1.15989434]
 [ 0.61020586 -1.27197275  1.03678902  0.62384542 -0.97978992  0.20922573]
 [ 0.86282711 -0.68231503 -1.29384543 -1.71820588 -0.54214425 -0.56365181]
 [-1.68474249  1.03592795  0.90891065  0.72005742 -0.13008552  1.51432042]]

8. Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

In [119]:
## Your code here down

# Create a 2D array of size 10x10 with random integers between 1 and 100
array = np.random.randint(1, 101, size=(10, 10))

print("Array:")
print(array)

# Replace values greater than 50 with 1 and all other values with 0
array[array <= 50] = 0
array[array > 50] = 1


print("\nArray:")
print(array)

## Your code here up

Array:
[[30 87 35 26 32 47 61 52 77 48]
 [ 1 52 93 83 19 16 21 48 96 60]
 [ 8 29 64 60 10 33 51 25 33 18]
 [96 44 21  4 81 32 74 20 50 91]
 [72 43  3 23 18 32 14 13 23 36]
 [32 91 59 11  3 95 83 64 41  2]
 [31 93 11 77  2  7 28 81 18 60]
 [62 46  2 30 41 64 72 81 58 94]
 [56 76  2 13 74 40  8 59 47 80]
 [ 9 19 43 40 70 14 13 82 76  4]]

Array:
[[0 1 0 0 0 0 1 1 1 0]
 [0 1 1 1 0 0 0 0 1 1]
 [0 0 1 1 0 0 1 0 0 0]
 [1 0 0 0 1 0 1 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 1 1 0 0]
 [0 1 0 1 0 0 0 1 0 1]
 [1 0 0 0 0 1 1 1 1 1]
 [1 1 0 0 1 0 0 1 0 1]
 [0 0 0 0 1 0 0 1 1 0]]

9. Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

In [120]:
## Your code here down

# Create a 1D array of size 50 with random floats between 0 and 1
array = np.random.random(50)

# Find the number of elements greater than 0.5
count = np.sum(array > 0.5)

print("Array:")
print(array)
print("\nNumber of elements greater than 0.5:", count)

## Your code here up

Array:
[0.77893245 0.2026953  0.81849884 0.20517621 0.88205888 0.13490698
 0.28706599 0.55584638 0.8779128  0.39685645 0.53534306 0.4521167
 0.77593193 0.21758622 0.1441706  0.64572726 0.85753645 0.67171231
 0.06950135 0.88295514 0.87555154 0.66953278 0.13364118 0.80880586
 0.28750678 0.36745011 0.20349464 0.31620305 0.8352718  0.42459299
 0.32654399 0.23208293 0.30913209 0.58974702 0.29349184 0.89864114
 0.85158366 0.0147814  0.75512881 0.61631021 0.11349474 0.27688678
 0.25432228 0.87789038 0.96033519 0.9545139  0.43385536 0.37974033
 0.31383459 0.98900476]

Number of elements greater than 0.5: 24

10. Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

In [121]:
## Your code here down

# Create a 2D array of size 5x5 with random floats between -1 and 1
array = np.random.uniform(-1, 1, size=(5, 5))

# Find the absolute difference between the maximum and minimum values in each row
row_diff = np.abs(np.max(array, axis=1) - np.min(array, axis=1))

print("Array:")
print(array)
print("\nAbsolute difference between maximum and minimum values in each row:")
print(row_diff)

## Your code here up

Array:
[[ 0.21138098  0.42538064 -0.1768553   0.60973494  0.55895534]
 [ 0.46929266  0.74015262 -0.33789449  0.64613167 -0.94017515]
 [-0.91498648  0.41773174 -0.41420138 -0.40671767 -0.30855566]
 [ 0.9077197   0.20437867  0.42403623 -0.40246667 -0.98575778]
 [-0.04034074 -0.02281423  0.98610585  0.61636202 -0.24369996]]

Absolute difference between maximum and minimum values in each row:
[0.78659025 1.68032777 1.33271823 1.89347748 1.22980581]

## Pandas

Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part.

In [122]:
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(40):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # rantom lat with 2 decimal points
        'temperature': round(random.uniform(18, 25), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 50), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)

In [123]:
df =pd.DataFrame(farms) # your code here
df.head()

  farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0    Farm 1   -102.20     51.77         24.1           43.8  dark brown
1    Farm 2   -101.01     51.15         20.3           46.3       brown
2    Farm 3   -102.58     51.86         19.2           20.4        None
3    Farm 4   -104.97     50.46         24.1           33.7        gray
4    Farm 5   -103.06     51.27         21.9           21.9        gray

1. Select the rows where the temperature is above 20 degrees Celsius.

In [124]:
## Your code here down
df[df['temperature']>20]

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -102.20     51.77         24.1           43.8  dark brown
1     Farm 2   -101.01     51.15         20.3           46.3       brown
3     Farm 4   -104.97     50.46         24.1           33.7        gray
4     Farm 5   -103.06     51.27         21.9           21.9        gray
5     Farm 6   -103.29     50.21         20.5           48.2       black
6     Farm 7   -102.81     50.45         23.7           31.5        None
9    Farm 10   -100.11     51.69         21.6           50.0        gray
10   Farm 11   -100.84     50.07         23.2           26.9        None
11   Farm 12   -101.71     50.91         23.9           21.9       black
13   Farm 14   -102.29     51.86         20.2           35.8       brown
15   Farm 16   -100.51     51.63         21.7           20.7       black
16   Farm 17   -100.83     51.87         22.1           39.2  dark brown
17   Farm 18   -102.83     51.24         22.1           41.8        gray
18   Farm 19   -103.79     50.55         24.6           36.2       brown
21   Farm 22   -100.66     50.00         24.6           30.2       brown
23   Farm 24   -104.27     51.82         23.0           36.9       brown
24   Farm 25   -103.64     50.95         21.6           33.1        gray
26   Farm 27   -101.36     50.99         25.0           27.2  dark brown
28   Farm 29   -100.14     50.69         20.9           37.4  dark brown
29   Farm 30   -103.48     50.56         21.9           27.2       black
30   Farm 31   -104.00     51.85         22.0           37.3        None
31   Farm 32   -104.04     51.16         21.0           39.2        None
32   Farm 33   -104.35     51.71         23.2           32.4        None
34   Farm 35   -103.56     51.92         22.7           49.9       brown
35   Farm 36   -103.45     50.64         22.9           35.0        gray
36   Farm 37   -102.86     50.43         22.8           24.1        gray
37   Farm 38   -101.48     51.95         23.9           38.3        None
38   Farm 39   -103.30     51.91         22.9           31.3        gray
39   Farm 40   -102.24     50.64         23.5           36.8  dark brown

2. Sort the DataFrame by precipitation in descending order.

In [125]:
## Your code here down
df.sort_values(by='precipitation', ascending=False)  # Descending order

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
9    Farm 10   -100.11     51.69         21.6           50.0        gray
34   Farm 35   -103.56     51.92         22.7           49.9       brown
22   Farm 23   -103.80     51.10         18.6           48.6        gray
5     Farm 6   -103.29     50.21         20.5           48.2       black
20   Farm 21   -101.67     51.26         20.0           47.7       black
33   Farm 34   -103.27     50.33         18.9           47.6        None
1     Farm 2   -101.01     51.15         20.3           46.3       brown
0     Farm 1   -102.20     51.77         24.1           43.8  dark brown
12   Farm 13   -102.05     50.98         18.0           42.5  dark brown
17   Farm 18   -102.83     51.24         22.1           41.8        gray
25   Farm 26   -104.58     51.78         19.6           40.5        None
27   Farm 28   -103.81     51.17         20.0           39.4  dark brown
31   Farm 32   -104.04     51.16         21.0           39.2        None
16   Farm 17   -100.83     51.87         22.1           39.2  dark brown
37   Farm 38   -101.48     51.95         23.9           38.3        None
8     Farm 9   -103.69     51.98         18.8           37.7        gray
28   Farm 29   -100.14     50.69         20.9           37.4  dark brown
30   Farm 31   -104.00     51.85         22.0           37.3        None
23   Farm 24   -104.27     51.82         23.0           36.9       brown
39   Farm 40   -102.24     50.64         23.5           36.8  dark brown
18   Farm 19   -103.79     50.55         24.6           36.2       brown
13   Farm 14   -102.29     51.86         20.2           35.8       brown
35   Farm 36   -103.45     50.64         22.9           35.0        gray
3     Farm 4   -104.97     50.46         24.1           33.7        gray
24   Farm 25   -103.64     50.95         21.6           33.1        gray
32   Farm 33   -104.35     51.71         23.2           32.4        None
6     Farm 7   -102.81     50.45         23.7           31.5        None
38   Farm 39   -103.30     51.91         22.9           31.3        gray
19   Farm 20   -100.38     51.67         18.2           30.5        None
21   Farm 22   -100.66     50.00         24.6           30.2       brown
26   Farm 27   -101.36     50.99         25.0           27.2  dark brown
29   Farm 30   -103.48     50.56         21.9           27.2       black
10   Farm 11   -100.84     50.07         23.2           26.9        None
14   Farm 15   -101.45     51.13         19.2           26.6  dark brown
7     Farm 8   -103.55     51.80         19.3           25.9        gray
36   Farm 37   -102.86     50.43         22.8           24.1        gray
11   Farm 12   -101.71     50.91         23.9           21.9       black
4     Farm 5   -103.06     51.27         21.9           21.9        gray
15   Farm 16   -100.51     51.63         21.7           20.7       black
2     Farm 3   -102.58     51.86         19.2           20.4        None

3. Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.

In [126]:
## Your code here down
df.loc[(df['farm_lat'] >= 51.00) & (df['farm_lat'] <= 51.15)]

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
1     Farm 2   -101.01     51.15         20.3           46.3       brown
14   Farm 15   -101.45     51.13         19.2           26.6  dark brown
22   Farm 23   -103.80     51.10         18.6           48.6        gray

 4. Calculate the standard deviation of precipitation for each soil type.

In [127]:
## Your code here down
std_deviation = df.groupby('soil_type')['precipitation'].std()

print("Standard Deviation of Precipitation for Each Soil Type:")
print(std_deviation)

## Your code here up

Standard Deviation of Precipitation for Each Soil Type:
soil_type
black         13.740197
brown          7.372223
dark brown     6.439707
gray           9.248685
Name: precipitation, dtype: float64

5. Calculate the cumulative sum of precipitation for each soil type.

In [128]:
## Your code here down
cumulative_sum = df.groupby('soil_type')['precipitation'].cumsum()

print("Cumulative Sum of Precipitation for Each Soil Type:")
print(cumulative_sum)

## Your code here up

Cumulative Sum of Precipitation for Each Soil Type:
0      43.8
1      46.3
2       NaN
3      33.7
4      55.6
5      48.2
6       NaN
7      81.5
8     119.2
9     169.2
10      NaN
11     70.1
12     86.3
13     82.1
14    112.9
15     90.8
16    152.1
17    211.0
18    118.3
19      NaN
20    138.5
21    148.5
22    259.6
23    185.4
24    292.7
25      NaN
26    179.3
27    218.7
28    256.1
29    165.7
30      NaN
31      NaN
32      NaN
33      NaN
34    235.3
35    327.7
36    351.8
37      NaN
38    383.1
39    292.9
Name: precipitation, dtype: float64

6. Determine the top 3 farms with the highest average temperature.

In [129]:
## Your code here down
# Calculate the average temperature for each farm
average_temp = df.groupby('farm_name')['temperature'].mean()

# Sort the farms based on average temperature in descending order
sorted_farms = average_temp.sort_values(ascending=False)

# Get the top 3 farms with the highest average temperature
top_3_farms = sorted_farms.head(3)

print("Top 3 Farms with the Highest Average Temperature:")
print(top_3_farms)

## Your code here up

Top 3 Farms with the Highest Average Temperature:
farm_name
Farm 27    25.0
Farm 22    24.6
Farm 19    24.6
Name: temperature, dtype: float64

7. Find famrs in each soil type that have the highest temperature.

In [130]:
## Your code here down
max_temp_farms = df.groupby('soil_type').apply(lambda x: x[x['temperature'] == x['temperature'].max()])

print("Farms with the Highest Temperature in Each Soil Type:")
print(max_temp_farms)

## Your code here up

Farms with the Highest Temperature in Each Soil Type:
              farm_name  farm_lon  farm_lat  temperature  precipitation  \
soil_type
black      11   Farm 12   -101.71     50.91         23.9           21.9
brown      18   Farm 19   -103.79     50.55         24.6           36.2
           21   Farm 22   -100.66     50.00         24.6           30.2
dark brown 26   Farm 27   -101.36     50.99         25.0           27.2
gray       3     Farm 4   -104.97     50.46         24.1           33.7

                soil_type
soil_type
black      11       black
brown      18       brown
           21       brown
dark brown 26  dark brown
gray       3         gray

8. Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

In [131]:
## Your code here down
total_precipitation = df['precipitation'].sum()

# Calculate the percentage contribution of each farm's precipitation
df['percentage_tot_prec'] = (df['precipitation'] / total_precipitation) * 100

print("DataFrame with Percentage Contribution of Precipitation:")
print(df)

## Your code here up

DataFrame with Percentage Contribution of Precipitation:
   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -102.20     51.77         24.1           43.8  dark brown
1     Farm 2   -101.01     51.15         20.3           46.3       brown
2     Farm 3   -102.58     51.86         19.2           20.4        None
3     Farm 4   -104.97     50.46         24.1           33.7        gray
4     Farm 5   -103.06     51.27         21.9           21.9        gray
5     Farm 6   -103.29     50.21         20.5           48.2       black
6     Farm 7   -102.81     50.45         23.7           31.5        None
7     Farm 8   -103.55     51.80         19.3           25.9        gray
8     Farm 9   -103.69     51.98         18.8           37.7        gray
9    Farm 10   -100.11     51.69         21.6           50.0        gray
10   Farm 11   -100.84     50.07         23.2           26.9        None
11   Farm 12   -101.71     50.91         23.9           21.9       black
12   Farm 13   -102.05     50.98         18.0           42.5  dark brown
13   Farm 14   -102.29     51.86         20.2           35.8       brown
14   Farm 15   -101.45     51.13         19.2           26.6  dark brown
15   Farm 16   -100.51     51.63         21.7           20.7       black
16   Farm 17   -100.83     51.87         22.1           39.2  dark brown
17   Farm 18   -102.83     51.24         22.1           41.8        gray
18   Farm 19   -103.79     50.55         24.6           36.2       brown
19   Farm 20   -100.38     51.67         18.2           30.5        None
20   Farm 21   -101.67     51.26         20.0           47.7       black
21   Farm 22   -100.66     50.00         24.6           30.2       brown
22   Farm 23   -103.80     51.10         18.6           48.6        gray
23   Farm 24   -104.27     51.82         23.0           36.9       brown
24   Farm 25   -103.64     50.95         21.6           33.1        gray
25   Farm 26   -104.58     51.78         19.6           40.5        None
26   Farm 27   -101.36     50.99         25.0           27.2  dark brown
27   Farm 28   -103.81     51.17         20.0           39.4  dark brown
28   Farm 29   -100.14     50.69         20.9           37.4  dark brown
29   Farm 30   -103.48     50.56         21.9           27.2       black
30   Farm 31   -104.00     51.85         22.0           37.3        None
31   Farm 32   -104.04     51.16         21.0           39.2        None
32   Farm 33   -104.35     51.71         23.2           32.4        None
33   Farm 34   -103.27     50.33         18.9           47.6        None
34   Farm 35   -103.56     51.92         22.7           49.9       brown
35   Farm 36   -103.45     50.64         22.9           35.0        gray
36   Farm 37   -102.86     50.43         22.8           24.1        gray
37   Farm 38   -101.48     51.95         23.9           38.3        None
38   Farm 39   -103.30     51.91         22.9           31.3        gray
39   Farm 40   -102.24     50.64         23.5           36.8  dark brown

    percentage_tot_prec
0              3.081035
1              3.256894
2              1.435003
3              2.370568
4              1.540518
5              3.390546
6              2.215813
7              1.821891
8              2.651941
9              3.517164
10             1.892234
11             1.540518
12             2.989589
13             2.518289
14             1.871131
15             1.456106
16             2.757456
17             2.940349
18             2.546427
19             2.145470
20             3.355374
21             2.124367
22             3.418683
23             2.595667
24             2.328362
25             2.848903
26             1.913337
27             2.771525
28             2.630838
29             1.913337
30             2.623804
31             2.757456
32             2.279122
33             3.348340
34             3.510129
35             2.462015
36             1.695273
37             2.694147
38             2.201745
39             2.588633

9. Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.

In [132]:
## Your code here down
df['precipitation_rank'] = df['precipitation'].rank(method='min')

print("DataFrame with Precipitation Ranks:")
print(df)

## Your code here up

DataFrame with Precipitation Ranks:
   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -102.20     51.77         24.1           43.8  dark brown
1     Farm 2   -101.01     51.15         20.3           46.3       brown
2     Farm 3   -102.58     51.86         19.2           20.4        None
3     Farm 4   -104.97     50.46         24.1           33.7        gray
4     Farm 5   -103.06     51.27         21.9           21.9        gray
5     Farm 6   -103.29     50.21         20.5           48.2       black
6     Farm 7   -102.81     50.45         23.7           31.5        None
7     Farm 8   -103.55     51.80         19.3           25.9        gray
8     Farm 9   -103.69     51.98         18.8           37.7        gray
9    Farm 10   -100.11     51.69         21.6           50.0        gray
10   Farm 11   -100.84     50.07         23.2           26.9        None
11   Farm 12   -101.71     50.91         23.9           21.9       black
12   Farm 13   -102.05     50.98         18.0           42.5  dark brown
13   Farm 14   -102.29     51.86         20.2           35.8       brown
14   Farm 15   -101.45     51.13         19.2           26.6  dark brown
15   Farm 16   -100.51     51.63         21.7           20.7       black
16   Farm 17   -100.83     51.87         22.1           39.2  dark brown
17   Farm 18   -102.83     51.24         22.1           41.8        gray
18   Farm 19   -103.79     50.55         24.6           36.2       brown
19   Farm 20   -100.38     51.67         18.2           30.5        None
20   Farm 21   -101.67     51.26         20.0           47.7       black
21   Farm 22   -100.66     50.00         24.6           30.2       brown
22   Farm 23   -103.80     51.10         18.6           48.6        gray
23   Farm 24   -104.27     51.82         23.0           36.9       brown
24   Farm 25   -103.64     50.95         21.6           33.1        gray
25   Farm 26   -104.58     51.78         19.6           40.5        None
26   Farm 27   -101.36     50.99         25.0           27.2  dark brown
27   Farm 28   -103.81     51.17         20.0           39.4  dark brown
28   Farm 29   -100.14     50.69         20.9           37.4  dark brown
29   Farm 30   -103.48     50.56         21.9           27.2       black
30   Farm 31   -104.00     51.85         22.0           37.3        None
31   Farm 32   -104.04     51.16         21.0           39.2        None
32   Farm 33   -104.35     51.71         23.2           32.4        None
33   Farm 34   -103.27     50.33         18.9           47.6        None
34   Farm 35   -103.56     51.92         22.7           49.9       brown
35   Farm 36   -103.45     50.64         22.9           35.0        gray
36   Farm 37   -102.86     50.43         22.8           24.1        gray
37   Farm 38   -101.48     51.95         23.9           38.3        None
38   Farm 39   -103.30     51.91         22.9           31.3        gray
39   Farm 40   -102.24     50.64         23.5           36.8  dark brown

    percentage_tot_prec  precipitation_rank
0              3.081035                33.0
1              3.256894                34.0
2              1.435003                 1.0
3              2.370568                17.0
4              1.540518                 3.0
5              3.390546                37.0
6              2.215813                14.0
7              1.821891                 6.0
8              2.651941                25.0
9              3.517164                40.0
10             1.892234                 8.0
11             1.540518                 3.0
12             2.989589                32.0
13             2.518289                19.0
14             1.871131                 7.0
15             1.456106                 2.0
16             2.757456                27.0
17             2.940349                31.0
18             2.546427                20.0
19             2.145470                12.0
20             3.355374                36.0
21             2.124367                11.0
22             3.418683                38.0
23             2.595667                22.0
24             2.328362                16.0
25             2.848903                30.0
26             1.913337                 9.0
27             2.771525                29.0
28             2.630838                24.0
29             1.913337                 9.0
30             2.623804                23.0
31             2.757456                27.0
32             2.279122                15.0
33             3.348340                35.0
34             3.510129                39.0
35             2.462015                18.0
36             1.695273                 5.0
37             2.694147                26.0
38             2.201745                13.0
39             2.588633                21.0

10. Normalize the temperature column to a range between 0 and 1 for each farm.

In [133]:
## Your code here down

# Calculate the minimum and maximum temperature for each farm
min_temp = df['temperature'].min()
max_temp = df['temperature'].max()


# Normalize the temperature column between 0 and 1 for each farm
df['temperature'] = (df['temperature'] - min_temp) / (max_temp - min_temp)

print("DataFrame with Normalized Temperature:")
print(df)

## Your code here up

DataFrame with Normalized Temperature:
   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -102.20     51.77     0.871429           43.8  dark brown
1     Farm 2   -101.01     51.15     0.328571           46.3       brown
2     Farm 3   -102.58     51.86     0.171429           20.4        None
3     Farm 4   -104.97     50.46     0.871429           33.7        gray
4     Farm 5   -103.06     51.27     0.557143           21.9        gray
5     Farm 6   -103.29     50.21     0.357143           48.2       black
6     Farm 7   -102.81     50.45     0.814286           31.5        None
7     Farm 8   -103.55     51.80     0.185714           25.9        gray
8     Farm 9   -103.69     51.98     0.114286           37.7        gray
9    Farm 10   -100.11     51.69     0.514286           50.0        gray
10   Farm 11   -100.84     50.07     0.742857           26.9        None
11   Farm 12   -101.71     50.91     0.842857           21.9       black
12   Farm 13   -102.05     50.98     0.000000           42.5  dark brown
13   Farm 14   -102.29     51.86     0.314286           35.8       brown
14   Farm 15   -101.45     51.13     0.171429           26.6  dark brown
15   Farm 16   -100.51     51.63     0.528571           20.7       black
16   Farm 17   -100.83     51.87     0.585714           39.2  dark brown
17   Farm 18   -102.83     51.24     0.585714           41.8        gray
18   Farm 19   -103.79     50.55     0.942857           36.2       brown
19   Farm 20   -100.38     51.67     0.028571           30.5        None
20   Farm 21   -101.67     51.26     0.285714           47.7       black
21   Farm 22   -100.66     50.00     0.942857           30.2       brown
22   Farm 23   -103.80     51.10     0.085714           48.6        gray
23   Farm 24   -104.27     51.82     0.714286           36.9       brown
24   Farm 25   -103.64     50.95     0.514286           33.1        gray
25   Farm 26   -104.58     51.78     0.228571           40.5        None
26   Farm 27   -101.36     50.99     1.000000           27.2  dark brown
27   Farm 28   -103.81     51.17     0.285714           39.4  dark brown
28   Farm 29   -100.14     50.69     0.414286           37.4  dark brown
29   Farm 30   -103.48     50.56     0.557143           27.2       black
30   Farm 31   -104.00     51.85     0.571429           37.3        None
31   Farm 32   -104.04     51.16     0.428571           39.2        None
32   Farm 33   -104.35     51.71     0.742857           32.4        None
33   Farm 34   -103.27     50.33     0.128571           47.6        None
34   Farm 35   -103.56     51.92     0.671429           49.9       brown
35   Farm 36   -103.45     50.64     0.700000           35.0        gray
36   Farm 37   -102.86     50.43     0.685714           24.1        gray
37   Farm 38   -101.48     51.95     0.842857           38.3        None
38   Farm 39   -103.30     51.91     0.700000           31.3        gray
39   Farm 40   -102.24     50.64     0.785714           36.8  dark brown

    percentage_tot_prec  precipitation_rank
0              3.081035                33.0
1              3.256894                34.0
2              1.435003                 1.0
3              2.370568                17.0
4              1.540518                 3.0
5              3.390546                37.0
6              2.215813                14.0
7              1.821891                 6.0
8              2.651941                25.0
9              3.517164                40.0
10             1.892234                 8.0
11             1.540518                 3.0
12             2.989589                32.0
13             2.518289                19.0
14             1.871131                 7.0
15             1.456106                 2.0
16             2.757456                27.0
17             2.940349                31.0
18             2.546427                20.0
19             2.145470                12.0
20             3.355374                36.0
21             2.124367                11.0
22             3.418683                38.0
23             2.595667                22.0
24             2.328362                16.0
25             2.848903                30.0
26             1.913337                 9.0
27             2.771525                29.0
28             2.630838                24.0
29             1.913337                 9.0
30             2.623804                23.0
31             2.757456                27.0
32             2.279122                15.0
33             3.348340                35.0
34             3.510129                39.0
35             2.462015                18.0
36             1.695273                 5.0
37             2.694147                26.0
38             2.201745                13.0
39             2.588633                21.0

In [134]:
print(max_temp)

25.0